// Code generated by go-swagger; DO NOT EDIT.

package presence

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// GetPresenceReader is a Reader for the GetPresence structure.
type GetPresenceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPresenceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPresenceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetPresenceForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPresenceNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPresenceOK creates a GetPresenceOK with default headers values
func NewGetPresenceOK() *GetPresenceOK {
	return &GetPresenceOK{}
}

/*GetPresenceOK handles this case with default header values.

The presence state for this user.
*/
type GetPresenceOK struct {
	Payload *GetPresenceOKBody
}

func (o *GetPresenceOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/{userId}/status][%d] getPresenceOK  %+v", 200, o.Payload)
}

func (o *GetPresenceOK) GetPayload() *GetPresenceOKBody {
	return o.Payload
}

func (o *GetPresenceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPresenceOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPresenceForbidden creates a GetPresenceForbidden with default headers values
func NewGetPresenceForbidden() *GetPresenceForbidden {
	return &GetPresenceForbidden{}
}

/*GetPresenceForbidden handles this case with default header values.

You are not allowed to see this user's presence status.
*/
type GetPresenceForbidden struct {
	Payload *GetPresenceForbiddenBody
}

func (o *GetPresenceForbidden) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/{userId}/status][%d] getPresenceForbidden  %+v", 403, o.Payload)
}

func (o *GetPresenceForbidden) GetPayload() *GetPresenceForbiddenBody {
	return o.Payload
}

func (o *GetPresenceForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPresenceForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPresenceNotFound creates a GetPresenceNotFound with default headers values
func NewGetPresenceNotFound() *GetPresenceNotFound {
	return &GetPresenceNotFound{}
}

/*GetPresenceNotFound handles this case with default header values.

There is no presence state for this user. This user may not exist or
isn't exposing presence information to you.
*/
type GetPresenceNotFound struct {
	Payload *GetPresenceNotFoundBody
}

func (o *GetPresenceNotFound) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/presence/{userId}/status][%d] getPresenceNotFound  %+v", 404, o.Payload)
}

func (o *GetPresenceNotFound) GetPayload() *GetPresenceNotFoundBody {
	return o.Payload
}

func (o *GetPresenceNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetPresenceNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetPresenceForbiddenBody A Matrix-level Error
swagger:model GetPresenceForbiddenBody
*/
type GetPresenceForbiddenBody struct {

	// An error code.
	// Required: true
	Errcode *string `json:"errcode"`

	// A human-readable error message.
	Error string `json:"error,omitempty"`
}

// Validate validates this get presence forbidden body
func (o *GetPresenceForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrcode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPresenceForbiddenBody) validateErrcode(formats strfmt.Registry) error {

	if err := validate.Required("getPresenceForbidden"+"."+"errcode", "body", o.Errcode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPresenceForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPresenceForbiddenBody) UnmarshalBinary(b []byte) error {
	var res GetPresenceForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPresenceNotFoundBody A Matrix-level Error
swagger:model GetPresenceNotFoundBody
*/
type GetPresenceNotFoundBody struct {

	// An error code.
	// Required: true
	Errcode *string `json:"errcode"`

	// A human-readable error message.
	Error string `json:"error,omitempty"`
}

// Validate validates this get presence not found body
func (o *GetPresenceNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrcode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPresenceNotFoundBody) validateErrcode(formats strfmt.Registry) error {

	if err := validate.Required("getPresenceNotFound"+"."+"errcode", "body", o.Errcode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPresenceNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPresenceNotFoundBody) UnmarshalBinary(b []byte) error {
	var res GetPresenceNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*GetPresenceOKBody get presence o k body
swagger:model GetPresenceOKBody
*/
type GetPresenceOKBody struct {

	// Whether the user is currently active
	CurrentlyActive bool `json:"currently_active,omitempty"`

	// The length of time in milliseconds since an action was performed
	// by this user.
	LastActiveAgo int64 `json:"last_active_ago,omitempty"`

	// This user's presence.
	// Required: true
	// Enum: [online offline unavailable]
	Presence *string `json:"presence"`

	// The state message for this user if one was set.
	StatusMsg string `json:"status_msg,omitempty"`
}

// Validate validates this get presence o k body
func (o *GetPresenceOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePresence(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getPresenceOKBodyTypePresencePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["online","offline","unavailable"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getPresenceOKBodyTypePresencePropEnum = append(getPresenceOKBodyTypePresencePropEnum, v)
	}
}

const (

	// GetPresenceOKBodyPresenceOnline captures enum value "online"
	GetPresenceOKBodyPresenceOnline string = "online"

	// GetPresenceOKBodyPresenceOffline captures enum value "offline"
	GetPresenceOKBodyPresenceOffline string = "offline"

	// GetPresenceOKBodyPresenceUnavailable captures enum value "unavailable"
	GetPresenceOKBodyPresenceUnavailable string = "unavailable"
)

// prop value enum
func (o *GetPresenceOKBody) validatePresenceEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, getPresenceOKBodyTypePresencePropEnum); err != nil {
		return err
	}
	return nil
}

func (o *GetPresenceOKBody) validatePresence(formats strfmt.Registry) error {

	if err := validate.Required("getPresenceOK"+"."+"presence", "body", o.Presence); err != nil {
		return err
	}

	// value enum
	if err := o.validatePresenceEnum("getPresenceOK"+"."+"presence", "body", *o.Presence); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPresenceOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPresenceOKBody) UnmarshalBinary(b []byte) error {
	var res GetPresenceOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
