// Code generated by go-swagger; DO NOT EDIT.

package room_participation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// SetTypingReader is a Reader for the SetTyping structure.
type SetTypingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetTypingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetTypingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewSetTypingTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetTypingOK creates a SetTypingOK with default headers values
func NewSetTypingOK() *SetTypingOK {
	return &SetTypingOK{}
}

/*SetTypingOK handles this case with default header values.

The new typing state was set.
*/
type SetTypingOK struct {
	Payload interface{}
}

func (o *SetTypingOK) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/rooms/{roomId}/typing/{userId}][%d] setTypingOK  %+v", 200, o.Payload)
}

func (o *SetTypingOK) GetPayload() interface{} {
	return o.Payload
}

func (o *SetTypingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetTypingTooManyRequests creates a SetTypingTooManyRequests with default headers values
func NewSetTypingTooManyRequests() *SetTypingTooManyRequests {
	return &SetTypingTooManyRequests{}
}

/*SetTypingTooManyRequests handles this case with default header values.

This request was rate-limited.
*/
type SetTypingTooManyRequests struct {
	Payload *SetTypingTooManyRequestsBody
}

func (o *SetTypingTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/rooms/{roomId}/typing/{userId}][%d] setTypingTooManyRequests  %+v", 429, o.Payload)
}

func (o *SetTypingTooManyRequests) GetPayload() *SetTypingTooManyRequestsBody {
	return o.Payload
}

func (o *SetTypingTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetTypingTooManyRequestsBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetTypingBody set typing body
swagger:model SetTypingBody
*/
type SetTypingBody struct {

	// The length of time in milliseconds to mark this user as typing.
	Timeout int64 `json:"timeout,omitempty"`

	// Whether the user is typing or not. If ``false``, the ``timeout``
	// key can be omitted.
	// Required: true
	Typing *bool `json:"typing"`
}

// Validate validates this set typing body
func (o *SetTypingBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTyping(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetTypingBody) validateTyping(formats strfmt.Registry) error {

	if err := validate.Required("typingState"+"."+"typing", "body", o.Typing); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetTypingBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetTypingBody) UnmarshalBinary(b []byte) error {
	var res SetTypingBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetTypingTooManyRequestsBody The rate limit was reached for this request
swagger:model SetTypingTooManyRequestsBody
*/
type SetTypingTooManyRequestsBody struct {

	// The M_LIMIT_EXCEEDED error code
	// Required: true
	Errcode *string `json:"errcode"`

	// A human-readable error message.
	Error string `json:"error,omitempty"`

	// The amount of time in milliseconds the client should wait
	// before trying the request again.
	RetryAfterMs int64 `json:"retry_after_ms,omitempty"`
}

// Validate validates this set typing too many requests body
func (o *SetTypingTooManyRequestsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrcode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetTypingTooManyRequestsBody) validateErrcode(formats strfmt.Registry) error {

	if err := validate.Required("setTypingTooManyRequests"+"."+"errcode", "body", o.Errcode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetTypingTooManyRequestsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetTypingTooManyRequestsBody) UnmarshalBinary(b []byte) error {
	var res SetTypingTooManyRequestsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
