// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// GetRoomTagsReader is a Reader for the GetRoomTags structure.
type GetRoomTagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRoomTagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRoomTagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetRoomTagsOK creates a GetRoomTagsOK with default headers values
func NewGetRoomTagsOK() *GetRoomTagsOK {
	return &GetRoomTagsOK{}
}

/*GetRoomTagsOK handles this case with default header values.

The list of tags for the user for the room.
*/
type GetRoomTagsOK struct {
	Payload *GetRoomTagsOKBody
}

func (o *GetRoomTagsOK) Error() string {
	return fmt.Sprintf("[GET /_matrix/client/unstable/user/{userId}/rooms/{roomId}/tags][%d] getRoomTagsOK  %+v", 200, o.Payload)
}

func (o *GetRoomTagsOK) GetPayload() *GetRoomTagsOKBody {
	return o.Payload
}

func (o *GetRoomTagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetRoomTagsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetRoomTagsOKBody get room tags o k body
swagger:model GetRoomTagsOKBody
*/
type GetRoomTagsOKBody struct {

	// tags
	Tags map[string]TagsAnon `json:"tags,omitempty"`
}

// Validate validates this get room tags o k body
func (o *GetRoomTagsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetRoomTagsOKBody) validateTags(formats strfmt.Registry) error {

	if swag.IsZero(o.Tags) { // not required
		return nil
	}

	for k := range o.Tags {

		if swag.IsZero(o.Tags[k]) { // not required
			continue
		}
		if val, ok := o.Tags[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetRoomTagsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetRoomTagsOKBody) UnmarshalBinary(b []byte) error {
	var res GetRoomTagsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*TagsAnon Tag
swagger:model TagsAnon
*/
type TagsAnon struct {

	// A number in a range ``[0,1]`` describing a relative
	// position of the room under the given tag.
	Order float32 `json:"order,omitempty"`

	// tags anon additional properties
	TagsAnonAdditionalProperties map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *TagsAnon) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// A number in a range ``[0,1]`` describing a relative
		// position of the room under the given tag.
		Order float32 `json:"order,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv TagsAnon

	rcv.Order = stage1.Order

	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "order")

	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.TagsAnonAdditionalProperties = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o TagsAnon) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// A number in a range ``[0,1]`` describing a relative
		// position of the room under the given tag.
		Order float32 `json:"order,omitempty"`
	}

	stage1.Order = o.Order

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.TagsAnonAdditionalProperties) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.TagsAnonAdditionalProperties)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this tags anon
func (o *TagsAnon) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *TagsAnon) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *TagsAnon) UnmarshalBinary(b []byte) error {
	var res TagsAnon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
