// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// SetAvatarURLReader is a Reader for the SetAvatarURL structure.
type SetAvatarURLReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SetAvatarURLReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSetAvatarURLOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 429:
		result := NewSetAvatarURLTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSetAvatarURLOK creates a SetAvatarURLOK with default headers values
func NewSetAvatarURLOK() *SetAvatarURLOK {
	return &SetAvatarURLOK{}
}

/*SetAvatarURLOK handles this case with default header values.

The avatar URL was set.
*/
type SetAvatarURLOK struct {
	Payload interface{}
}

func (o *SetAvatarURLOK) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/profile/{userId}/avatar_url][%d] setAvatarUrlOK  %+v", 200, o.Payload)
}

func (o *SetAvatarURLOK) GetPayload() interface{} {
	return o.Payload
}

func (o *SetAvatarURLOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSetAvatarURLTooManyRequests creates a SetAvatarURLTooManyRequests with default headers values
func NewSetAvatarURLTooManyRequests() *SetAvatarURLTooManyRequests {
	return &SetAvatarURLTooManyRequests{}
}

/*SetAvatarURLTooManyRequests handles this case with default header values.

This request was rate-limited.
*/
type SetAvatarURLTooManyRequests struct {
	Payload *SetAvatarURLTooManyRequestsBody
}

func (o *SetAvatarURLTooManyRequests) Error() string {
	return fmt.Sprintf("[PUT /_matrix/client/unstable/profile/{userId}/avatar_url][%d] setAvatarUrlTooManyRequests  %+v", 429, o.Payload)
}

func (o *SetAvatarURLTooManyRequests) GetPayload() *SetAvatarURLTooManyRequestsBody {
	return o.Payload
}

func (o *SetAvatarURLTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(SetAvatarURLTooManyRequestsBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SetAvatarURLBody set avatar URL body
swagger:model SetAvatarURLBody
*/
type SetAvatarURLBody struct {

	// The new avatar URL for this user.
	AvatarURL string `json:"avatar_url,omitempty"`
}

// Validate validates this set avatar URL body
func (o *SetAvatarURLBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *SetAvatarURLBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetAvatarURLBody) UnmarshalBinary(b []byte) error {
	var res SetAvatarURLBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*SetAvatarURLTooManyRequestsBody The rate limit was reached for this request
swagger:model SetAvatarURLTooManyRequestsBody
*/
type SetAvatarURLTooManyRequestsBody struct {

	// The M_LIMIT_EXCEEDED error code
	// Required: true
	Errcode *string `json:"errcode"`

	// A human-readable error message.
	Error string `json:"error,omitempty"`

	// The amount of time in milliseconds the client should wait
	// before trying the request again.
	RetryAfterMs int64 `json:"retry_after_ms,omitempty"`
}

// Validate validates this set avatar URL too many requests body
func (o *SetAvatarURLTooManyRequestsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateErrcode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SetAvatarURLTooManyRequestsBody) validateErrcode(formats strfmt.Registry) error {

	if err := validate.Required("setAvatarUrlTooManyRequests"+"."+"errcode", "body", o.Errcode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SetAvatarURLTooManyRequestsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SetAvatarURLTooManyRequestsBody) UnmarshalBinary(b []byte) error {
	var res SetAvatarURLTooManyRequestsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
