// Code generated by go-swagger; DO NOT EDIT.

package user_data

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnbind3pidFromAccountParams creates a new Unbind3pidFromAccountParams object
// with the default values initialized.
func NewUnbind3pidFromAccountParams() *Unbind3pidFromAccountParams {
	var ()
	return &Unbind3pidFromAccountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUnbind3pidFromAccountParamsWithTimeout creates a new Unbind3pidFromAccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUnbind3pidFromAccountParamsWithTimeout(timeout time.Duration) *Unbind3pidFromAccountParams {
	var ()
	return &Unbind3pidFromAccountParams{

		timeout: timeout,
	}
}

// NewUnbind3pidFromAccountParamsWithContext creates a new Unbind3pidFromAccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewUnbind3pidFromAccountParamsWithContext(ctx context.Context) *Unbind3pidFromAccountParams {
	var ()
	return &Unbind3pidFromAccountParams{

		Context: ctx,
	}
}

// NewUnbind3pidFromAccountParamsWithHTTPClient creates a new Unbind3pidFromAccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUnbind3pidFromAccountParamsWithHTTPClient(client *http.Client) *Unbind3pidFromAccountParams {
	var ()
	return &Unbind3pidFromAccountParams{
		HTTPClient: client,
	}
}

/*Unbind3pidFromAccountParams contains all the parameters to send to the API endpoint
for the unbind3pid from account operation typically these are written to a http.Request
*/
type Unbind3pidFromAccountParams struct {

	/*Body*/
	Body Unbind3pidFromAccountBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) WithTimeout(timeout time.Duration) *Unbind3pidFromAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) WithContext(ctx context.Context) *Unbind3pidFromAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) WithHTTPClient(client *http.Client) *Unbind3pidFromAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) WithBody(body Unbind3pidFromAccountBody) *Unbind3pidFromAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the unbind3pid from account params
func (o *Unbind3pidFromAccountParams) SetBody(body Unbind3pidFromAccountBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *Unbind3pidFromAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
